### ISSUE TITLE
Fix error handling in fetch def

### ISSUE THREAD

**Issue by gojideth** [Ghurtchu/COUNTributions#1]
On [Main.scala ](https://github.com/Ghurtchu/COUNTributions/blob/main/src/main/scala/com/rockthejvm/Main.scala#L68C8-L68C35) it is missing the prefix `$`. It should be:  `error"$other"`

**Comment by Ghurtchu** [comment]
Hey! Thanks for noticing that, let's merge 🚀

**Comment by gojideth** [comment]
No prob! Great article, a little bit tough since I've never tried actual Cats 😸

**Comment by Ghurtchu** [comment]
@gojideth Yhanks! Yeah it was not so simple for me to write this small app too, but I myself learned some new things there.

Btw, if you'd like to collaborate on weekends, you can contribute to my other project: https://github.com/Ghurtchu/blabbermouth

It's mostly for learning purposes, there's some documentation but the JSON models are a bit outdated. If you find it interesting we can collaborate via Discord or something else
